SERVERS = {
    "Asura": 28,
    "Bahamut": 1,
    "Bismarck": 25,
    "Carbuncle": 6,
    "Cerberus": 23,
    "Fenrir": 7,
    "Lakshmi": 27,
    "Leviathan": 11,
    "Odin": 12,
    "Phoenix": 5,
    "Quetzalcoatl": 16,
    "Ragnarok": 20,
    "Shiva": 2,
    "Siren": 17,
    "Sylph": 8,
    "Valefor": 9,
}